import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCart } from '../contexts/CartContext';
import { motion } from 'framer-motion';
import { Trash2, Plus, Minus } from 'lucide-react';
import { Button } from '../components/ui/Button';
export function CartPage() {
    const { cart, removeFromCart, updateQuantity, getTotalPrice, clearCart } = useCart();
    if (cart.length === 0) {
        return (_jsx("div", { className: "flex flex-col items-center justify-center min-h-[60vh]", children: _jsxs(motion.div, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, className: "text-center", children: [_jsx("h2", { className: "mb-4 text-3xl font-bold text-gray-800", children: "Your Cart is Empty" }), _jsx("p", { className: "mb-6 text-gray-600", children: "Looks like you haven't added any items to your cart yet." }), _jsx(Button, { variant: "primary", onClick: () => window.location.href = '/products', children: "Continue Shopping" })] }) }));
    }
    return (_jsxs("div", { className: "container px-4 py-8 mx-auto", children: [_jsx("h1", { className: "mb-8 text-4xl font-bold text-center", children: "Your Shopping Cart" }), _jsxs("div", { className: "grid gap-8 md:grid-cols-3", children: [_jsx("div", { className: "space-y-4 md:col-span-2", children: cart.map((item) => (_jsxs(motion.div, { initial: { opacity: 0, x: -50 }, animate: { opacity: 1, x: 0 }, className: "flex items-center p-4 bg-white rounded-lg shadow-md", children: [item.imageUrl && (_jsx("img", { src: item.imageUrl, alt: item.name, className: "object-cover w-24 h-24 mr-4 rounded-md" })), _jsxs("div", { className: "flex-grow", children: [_jsx("h3", { className: "text-xl font-semibold", children: item.name }), _jsxs("p", { className: "text-gray-600", children: ["$", item.price.toFixed(2)] })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Button, { variant: "outline", className: "p-2", onClick: () => updateQuantity(item.id, item.quantity - 1), children: _jsx(Minus, { size: 16 }) }), _jsx("span", { className: "px-4", children: item.quantity }), _jsx(Button, { variant: "outline", className: "p-2", onClick: () => updateQuantity(item.id, item.quantity + 1), children: _jsx(Plus, { size: 16 }) }), _jsx(Button, { variant: "secondary", className: "p-2 ml-4", onClick: () => removeFromCart(item.id), children: _jsx(Trash2, { size: 16 }) })] })] }, item.id))) }), _jsxs("div", { className: "p-6 bg-white rounded-lg shadow-md", children: [_jsx("h2", { className: "mb-4 text-2xl font-bold", children: "Order Summary" }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Total Items" }), _jsx("span", { children: cart.reduce((total, item) => total + item.quantity, 0) })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Subtotal" }), _jsxs("span", { children: ["$", getTotalPrice().toFixed(2)] })] }), _jsxs("div", { className: "flex justify-between mt-4 text-xl font-bold", children: [_jsx("span", { children: "Total" }), _jsxs("span", { children: ["$", getTotalPrice().toFixed(2)] })] })] }), _jsxs("div", { className: "mt-6 space-y-2", children: [_jsx(Button, { variant: "primary", fullWidth: true, className: "mb-2", children: "Proceed to Checkout" }), _jsx(Button, { variant: "outline", fullWidth: true, onClick: clearCart, children: "Clear Cart" })] })] })] })] }));
}
